drop table course_enrollment cascade constraints;

drop table course cascade constraints;


  CREATE TABLE "JPA"."COURSE" 
   (	"COURSEID" NUMBER(19,0) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"TITLE" VARCHAR2(255 CHAR), 
	"TUTORID" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("COURSEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FKQQC376M0UJGH12JJX9KPGL51W" FOREIGN KEY ("TUTORID")
	  REFERENCES "JPA"."TUTOR" ("TUTORID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



  CREATE TABLE "JPA"."COURSE_ENROLLMENT" 
   (	"ENROLLED_DATE" DATE, 
	"COURSEID" NUMBER(19,0), 
	"ENROLLMENTID" NUMBER(19,0) NOT NULL ENABLE, 
	"STATUS" NUMBER(19,0), 
	"STUDENTID" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("ENROLLMENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FKP36PS8RU6P0K21S65FKNS1657" FOREIGN KEY ("COURSEID")
	  REFERENCES "JPA"."COURSE" ("COURSEID") ENABLE, 
	 CONSTRAINT "FKL0Q0L4SK8COVUQDYI4JKFYD0M" FOREIGN KEY ("STUDENTID")
	  REFERENCES "JPA"."STUDENT" ("SUTDENTID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

